# Generated by Django 5.2.5 on 2026-05-20 05:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('fund_name', models.CharField(blank=True, max_length=255)),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('section', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Case Study Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('key', models.CharField(db_index=True, max_length=768, primary_key=True, serialize=False)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('data_type', models.CharField(blank=True, choices=[('text', 'Text'), ('blob', 'Blob')], max_length=10)),
                ('blob_data', models.FileField(blank=True, null=True, upload_to='resource_blobs/')),
                ('text_data', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('target_spec', models.JSONField(blank=True, null=True)),
                ('target_object_id', models.CharField(blank=True, default='', max_length=36)),
                ('status', models.CharField(choices=[('seeded', 'Seeded'), ('extracted', 'Extracted'), ('mined', 'Mined'), ('transformed', 'Transformed'), ('loaded', 'Loaded')], default='seeded', max_length=20)),
                ('seeded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('mined_at', models.DateTimeField(blank=True, null=True)),
                ('transformed_at', models.DateTimeField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_resources', to='tutorial.resource')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
