# Generated by Django 5.2.5 on 2025-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_authorprofile_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteresource',
            name='key',
            field=models.CharField(db_index=True, max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concreteresource',
            name='target_object_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
