name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.1", "5.2"]
        exclude:
          # Python 3.13 doesn't support Django 4.2
          - python-version: "3.13"
            django-version: "4.2"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install tox
      run: uv tool install tox --with tox-gh-actions

    - name: Run tests with tox
      run: tox
      env:
        DJANGO_VERSION: ${{ matrix.django-version }}

  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check: [lint, type]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install tox
      run: uv tool install tox

    - name: Run ${{ matrix.check }}
      run: tox -e ${{ matrix.check }}
